repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args: [--select, ALL, --fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=88, --check]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black', '--line-length=88', '--check', '--diff']

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|css|scss|json|yaml|yml|md)$
        exclude: package-lock\.json

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@^8.56.0
          - '@typescript-eslint/eslint-plugin@^6.0.0'
          - '@typescript-eslint/parser@^6.0.0'

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: python-compile-check
        name: 'Python syntax check'
        entry: bash -c 'python -m py_compile $(git ls-files "*.py")'
        language: system
        files: \.py$
        pass_filenames: false
      - id: frontend-lint
        name: 'Frontend linting'
        entry: bash -c 'cd . && npm run lint'
        language: system
        files: \.(js|jsx|ts|tsx)$
        pass_filenames: false
      - id: frontend-typecheck
        name: 'Frontend type checking'
        entry: bash -c 'cd . && npm run typecheck'
        language: system
        files: \.(ts|tsx)$
        pass_filenames: false
      - id: no_stubs_allowed
        name: 'No TODO/FIXME/pass stubs allowed'
        entry: bash -c 'if grep -rn "^\s*pass\s*$\|TODO\|FIXME" --include="*.py" --include="*.js" --include="*.ts" --include="*.tsx" .; then echo "❌ Found TODO/FIXME/pass stubs - implement proper code"; exit 1; fi'
        language: system
        files: \.(py|js|ts|tsx)$
        always_run: true
      - id: pytest
        name: pytest
        entry: pytest
        language: python
        types: [python]
        pass_filenames: false
        always_run: true
        args: [--cov=backend, --cov-report=term-missing, --cov-fail-under=75]

default_language_version:
  python: python3.13
