global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'usage-metering'
    static_configs:
      - targets: ['usage-metering:8005']
    metrics_path: '/metrics/usage'
    scrape_interval: 30s
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
