# Prometheus configuration for SCORPIUS monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']

scrape_configs:
  # SCORPIUS API metrics
  - job_name: 'scorpius-api'
    static_configs:
      - targets: ['scorpius-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL metrics (if exporter is configured)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  # System metrics (if node_exporter is configured)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
