global:
  scrape_interval: 15s     # Set the scrape interval to every 15 seconds
  evaluation_interval: 15s # Evaluate rules every 15 seconds
  scrape_timeout: 10s      # Timeout before considering a scrape failed

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# Scrape configurations
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'honeypot-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']
    
  - job_name: 'honeypot-worker'
    metrics_path: '/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['worker:8888']

  # Monitor MongoDB
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo-exporter:9216']

  # Monitor Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
