# Scorpius Enterprise Configuration

# Platform Settings
log_level: INFO
log_file: /data/logs/scorpius.log
data_directory: /data
temp_directory: /tmp/scorpius

# Enterprise Features
enable_clustering: true
enable_high_availability: true
backup_schedule: "0 2 * * *"  # Daily at 2 AM

# Cluster Configuration
cluster_nodes:
  - "scorpius-node-1:8000"
  - "scorpius-node-2:8000"
  - "scorpius-node-3:8000"

# Quantum Cryptography Configuration
quantum_config:
  default_algorithm: "lattice_based"
  default_security_level: 3
  key_rotation_interval: 86400  # 24 hours in seconds
  enable_quantum_key_distribution: true
  lattice_parameters:
    modulus: 2048
    noise_distribution: "gaussian"
    security_parameter: 128

# Security Engine Configuration
security_config:
  enable_ai_detection: true
  enable_mev_protection: true
  enable_formal_verification: true
  ai_model_path: "/data/models/security_ai.pkl"
  threat_intelligence_feeds:
    - "https://feeds.threatintel.io/quantum-threats"
    - "https://api.blockchain-security.com/threats"

# Analytics Configuration
analytics_config:
  retention_days: 365
  enable_real_time_analytics: true
  dashboard_refresh_interval: 30
  export_formats:
    - "json"
    - "csv"
    - "pdf"

# Integration Hub Configuration
integration_config:
  enable_workflows: true
  max_concurrent_workflows: 10
  workflow_timeout: 300
  enable_event_streaming: true

# Monitoring Configuration
monitoring_config:
  enable_health_checks: true
  health_check_interval: 30
  enable_metrics_collection: true
  metrics_retention_days: 30
  alert_endpoints:
    - "webhook://alerts.company.com/scorpius"
    - "email://admin@company.com"
