# Gitleaks configuration for Scorpius
title = "Scorpius Security Configuration"

[extend]
# Use default rules as base
useDefault = true

[[rules]]
id = "scorpius-private-key"
description = "Scorpius private keys"
regex = '''(?i)(private[_-]?key|priv[_-]?key|secret[_-]?key)["']?\s*[:=]\s*["']?(0x[a-fA-F0-9]{64})'''
keywords = [
    "private_key",
    "private-key",
    "privatekey",
    "secret_key",
]

[[rules]]
id = "scorpius-api-key"
description = "Scorpius API keys"
regex = '''(?i)(api[_-]?key|access[_-]?token|secret[_-]?token)["']?\s*[:=]\s*["']?([a-zA-Z0-9]{32,})'''
keywords = [
    "api_key",
    "api-key",
    "apikey",
    "access_token",
    "secret_token",
]

[allowlist]
description = "Allowlist for legitimate Ethereum addresses and test values"

# Allow common Ethereum contract addresses (not private keys)
regexes = [
    '''0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2''',  # WETH contract
    '''0x6B175474E89094C44Da98b954EedeAC495271d0F''',  # DAI contract
    '''0xA0b86a33E6f8A7F56e8e0CC''',                    # USDC placeholder
    '''invalid_token''',                                # Test token
    '''test[_-]?token''',                               # Test tokens
    '''0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80''',  # Hardhat default
]

# Allow test files and examples
paths = [
    '''.*\.example$''',
    '''.*test.*''',
    '''.*attic/.*''',
]
