# Fly.io configuration for Scorpius Backend - Production Environment
app = "scorpius-backend-prod"
primary_region = "ord"
kill_signal = "SIGINT"
kill_timeout = "10s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile.prod"

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "WARNING"
  PORT = "8000"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 2
  max_machines_running = 10
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "15s"
    interval = "60s"
    method = "GET"
    timeout = "10s"
    path = "/health"

[vm]
  cpu_kind = "performance"
  cpus = 2
  memory_mb = 2048

[metrics]
  port = 9091
  path = "/metrics"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 2000
    soft_limit = 1000

# Auto-scaling configuration
[[vm]]
  size = "shared-cpu-2x"
  processes = ["app"]

[deploy]
  strategy = "rolling"
  max_unavailable = 0.5

# Health checks
[[checks]]
  name = "backend_health"
  type = "http"
  interval = "30s"
  timeout = "5s"
  path = "/health"

[[checks]]
  name = "database_connectivity"
  type = "http"
  interval = "60s"
  timeout = "10s"
  path = "/health/db"

# Production secrets (set via: fly secrets set KEY=value)
# DATABASE_URL (production PostgreSQL)
# SECRET_KEY (strong production key)
# JWT_SECRET_KEY (strong production key)
# REDIS_URL (production Redis)
# OPENAI_API_KEY
# ANTHROPIC_API_KEY
# SENTRY_DSN
