global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "honeypot-api"
    static_configs:
      - targets: ["honeypot-api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "scanner-api"
    static_configs:
      - targets: ["scanner-api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s

  - job_name: "mempool-api"
    static_configs:
      - targets: ["mempool-api:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
