apiVersion: v2
name: scorpius
description: Scorpius Enterprise Platform Helm Chart
type: application
version: 0.1.0
appVersion: "1.0"
home: https://github.com/scorpius/enterprise-platform
sources:
  - https://github.com/scorpius/enterprise-platform
maintainers:
  - name: Scorpius Team
    email: team@scorpius.dev
keywords:
  - blockchain
  - defi
  - mev
  - security
  - monitoring
dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: 17.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: 20.x.x
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: 6.x.x
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
